name: Send a Discord message when new Youtube videos update
on:
  youtube:
    channel_id:
      - UCIdFnxf_vx6gqZO5Nh-kEjg
jobs:
  discord:
    name: Send a message to discord
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_AHS }}
          DISCORD_USERNAME: ${{ secrets.DISCORD_USERNAME_AHS }}
          DISCORD_AVATAR: ${{ secrets.DISCORD_AVATAR_AHS }}
        uses: Ilshidur/action-discord@master
        with:
          args: "`American Headache Society - YouTube`'\n'**${{on.youtube.outputs.title}}**'\n'${{on.youtube.outputs.link}}"
