name: Send a Discord message when new Youtube videos update
on:
  youtube:
    channel_id:
      - UC-ooNEgHgaMCI9gmPjItcZw
jobs:
  discord:
    name: Send a message to discord
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_AMF }}
          DISCORD_USERNAME: ${{ secrets.DISCORD_USERNAME_AMF }}
          DISCORD_AVATAR: ${{ secrets.DISCORD_AVATAR_AMF }}
        uses: Ilshidur/action-discord@master
        with:
          args: "`American Migraine Foundation - YouTube`'\n'**${{on.youtube.outputs.title}}**'\n'${{on.youtube.outputs.link}}"
