name: Send a Discord message when new Youtube videos update
on:
  youtube:
    channel_id:
      - UCWOEbyoEjoIXH9p3awr3I-g
jobs:
  discord:
    name: Send a message to discord
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_JOURNAL }}
          DISCORD_USERNAME: ${{ secrets.DISCORD_USERNAME_JOURNAL }}
          DISCORD_AVATAR: ${{ secrets.DISCORD_AVATAR_JOURNAL }}
        uses: Ilshidur/action-discord@master
        with:
          args: "`Headache Journal - YouTube`'\n'**${{on.youtube.outputs.title}}**'\n'${{on.youtube.outputs.link}}"
