name: Send a Discord message when new Youtube videos update
on:
  youtube:
    channel_id:
      - UC_7e4MOHTiBk24eMh2wsH3A
jobs:
  discord:
    name: Send a message to discord
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_IHS }}
          DISCORD_USERNAME: ${{ secrets.DISCORD_USERNAME_IHS }}
          DISCORD_AVATAR: ${{ secrets.DISCORD_AVATAR_IHS }}
        uses: Ilshidur/action-discord@master
        with:
          args: "`International Headache Society - YouTube`'\n'**${{on.youtube.outputs.title}}**'\n'${{on.youtube.outputs.link}}"
