name: Send a Discord message when new Youtube videos update
on:
  youtube:
    channel_id:
      - UCHf0SCPRVXdlzspBs1AJp2g
jobs:
  discord:
    name: Send a message to discord
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_NHF }}
          DISCORD_USERNAME: ${{ secrets.DISCORD_USERNAME_NHF }}
          DISCORD_AVATAR: ${{ secrets.DISCORD_AVATAR_NHF }}
        uses: Ilshidur/action-discord@master
        with:
          args: "`National Headache Foundation - YouTube`'\n'**${{on.youtube.outputs.title}}**'\n'${{on.youtube.outputs.link}}"
